[project]
name = "churn-predictor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ahmed", email = "ahmad_801a@ai.kfs.edu.eg" }
]
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.11.2",
    "mlflow>=3.16.1",
    "numpy>=2.4.6",
    "pandas>=3.0.6",
    "scikit-learn>=1.9.1",
    "seaborn>=0.13.2",
]

[project.scripts]
churn-predictor = "churn_predictor:main"

[build-system]
requires = ["uv_build>=0.12.22,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.4.0",
    "jupyter>=1.1.1",
    "pytest>=9.1.1",
    "ruff>=0.16.10",
]
